name: Site Testing

on: 
 pull_request:
  branches:
   - main
 workflow_dispatch:

jobs:

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - name: Run Markdown Lint
        uses: docker://ghcr.io/github/super-linter:slim-v4
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_MARKDOWN: true
          DEFAULT_BRANCH: main

  build:
    name: Test site
    runs-on: ubuntu-latest
    needs: [markdownlint]
    steps:
    - name: Checkout main
      uses: actions/checkout@v3.0.0
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.16.1
      env:
        BUILD_ONLY: true
        CHECK_LINKS: true
        BUILD_DIR: .
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
