on:
  push:
    branches:
      - main
name: Build and deploy on push
jobs:
  build:
    name: zbrox/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: zbrox/zola-deploy-action
      uses: zbrox/zola-deploy-action@main
      env:
        TOKEN: ${{ secrets.TOKEN }}
